controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    steer_position_controller:
      type: position_controllers/JointGroupPositionController


wheel_velocity_controller:
  ros__parameters:
    joints:
      - name1
      - name2
      - name3
      - name4


steer_position_controller:
  ros__parameters:
    joints:
      - front_left_steer_joint
      - front_right_steer_joint
      - rear_left_steer_joint
      - rear_right_steer_joint
